import { Roboto } from "next/font/google";
import "./globals.css";
const roboto = Roboto({ subsets: ["latin"],weight:['400','500','700'] });
import Header from '../Components/Header'
import Footer from '../Components/Footer'
import AppProvider from '../Components/AppProvider'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-6xl  mx-auto px-4">
        <AppProvider >
        <Header/>
        {children}
        <Footer/>
        </AppProvider>
        </main>
        </body>
    </html>
  );
}

